name: test.shop.pl
recipe: lamp

proxy:
  appserver:
    - test.shop.pl.lndo.site
  pma:
    - phpmyadmin.lndo.site
  mailhog:
    - mailhog.lndo.site

config:
  php: '8.1'
  via: apache
  webroot: www
  xdebug: true

  # To force Composer v1
  # composer_version: '1.10.24'

  config:
    php: config/php.ini

# Disable key loading - https://docs.lando.dev/config/ssh.html#customizing
keys: false

services:
  appserver:
    ports:
    # A nice handy known-local port  http://localhost:8080
      - '8080:80'

    # Bind my exposes services to all intefaces
    #  - "0.0.0.0::80"

    build_as_root:
      # Apache mod headers
      - a2enmod headers

      # Install xdebug-2.9.8, wait until Xdebug 3 is fully tested
      # - pecl uninstall xdebug
      # - pecl install xdebug-2.9.8

  database:
    type: mysql
    # type: mysql:5.7
    # type: mysql:8.0
    # config:
    #   database: config/mysql8.cnf
    portforward: 3306
    creds:
      user: ultrasshop
      password: prestashop!12345
      database: ultrasshop

  pma:
    type: phpmyadmin

  mailhog:
    type: mailhog
    portforward: 1025
    hogfrom:
      - appserver

tooling:

  install:
    service: appserver
    description: "Command to install PrestaShop (You must download and copy the prestashop.zip file into the www folder first)."
    cmd:
      - sh config/pre_install.sh
      - php config/install_ps.php
      - sh config/post_install.sh
